# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems: [jekyll-paginate, rouge]

future: true

# Site settings
title: Max Antonucci
email: maxx1128@gmail.com
description: >
  I code, write, design, analyze, often breathe, always philosophize.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maxwellantonucci.com/" # the base hostname & protocol for your site
permalink: /blog/:title/
paginate: 12,
paginate_path: "/blog/page:num/"

sass:
  style: compressed

# Build settings
markdown: kramdown
highlighter: rouge


# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules
  - package.json
  - gulpfile.js