# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Max Antonucci
description: > # this means to ignore newlines until "baseurl:"
  Journalist turned front-end coder.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maxwellantonucci.com" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: _sass

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules
  - package.json
  - gulpfile.js



# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap

# Styleguide settings
collections:
  styleguide:
    output: true

# Sensible defaults
defaults:
  -
    scope:
      path: ""
      type: "styleguide"
    values:
      layout: "blank"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:year/:month/:day/:title.html
