# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems: [jekyll-paginate]

# Site settings
title: Max Antonucci
description: > # this means to ignore newlines until "baseurl:"
  Journalist turned front-end coder.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maxwellantonucci.com" # the base hostname & protocol for your site

paginate: 6
paginate_path: "/blog/page:num/"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
exclude:
  - README.md
  - CNAME

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Sensible defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:year/:month/:day/:title.html

plugins_dir:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap